/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "NUSenseData.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
    #error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(message_Servo, message_Servo, AUTO)


PB_BIND(message_IMU, message_IMU, AUTO)


PB_BIND(message_IMU_fvec3, message_IMU_fvec3, AUTO)


PB_BIND(message_nusense, message_nusense, 2)


PB_BIND(message_nusense_ServoMapEntry, message_nusense_ServoMapEntry, AUTO)
