/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "NUSenseData.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(message_platform_Servo, message_platform_Servo, AUTO)


PB_BIND(message_platform_IMU, message_platform_IMU, AUTO)


PB_BIND(message_platform_IMU_fvec3, message_platform_IMU_fvec3, AUTO)


PB_BIND(message_platform_NUSense, message_platform_NUSense, 2)


PB_BIND(message_platform_NUSense_ServoMapEntry, message_platform_NUSense_ServoMapEntry, AUTO)



