/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "usb/protobuf/ServoTarget.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(message_actuation_ServoTarget, message_actuation_ServoTarget, AUTO)


PB_BIND(message_actuation_ServoTargets, message_actuation_ServoTargets, 2)



