/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "ServoTarget.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(message_actuation_ServoTarget, message_actuation_ServoTarget, AUTO)


PB_BIND(message_actuation_ServoTargets, message_actuation_ServoTargets, 2)


PB_BIND(message_actuation_SubcontrollerServoTarget, message_actuation_SubcontrollerServoTarget, AUTO)


PB_BIND(message_actuation_SubcontrollerServoTargets, message_actuation_SubcontrollerServoTargets, 2)



